services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    volumes:
      - ./project/seed:/home/seed
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  migrate:
    image: flyway/flyway:9.8.1
    container_name: migrate
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./project/migrations:/flyway/sql
    depends_on:
      - postgres

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/api/openapi.yaml
    volumes:
      - ./project/api:/api
