openapi: 3.0.0

info:
  title: Go API
  description: local go api
  version: 1.0.0

servers:
  - url: http://localhost:5000

components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
      required:
        - status

    Actor:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name

    SpecificDateEvent:
      type : object
      properties:
        date:
          type: string
        customTitle:
          type: string
      required:
        - date
        - customTitle

    AnimeContent:
      type: object
      properties:
        contentId:
          type: string
        title:
          type: string
        description:
          type: string
        year:
          type: integer
        season:
          type: string
      required:
        - contentId
        - title
        - description
        - year
        - season

    RadioContent:
      type: object
      properties:
        contentId:
          type: string
        title:
          type: string
        description:
          type: string
        scheduleType:
          type: string
        startDate:
          type: string
        endDate:
          type: string
      required:
        - contentId
        - title
        - description
        - scheduleType
        - startDate
        - endDate

    LiveContent:
      type: object
      properties:
        contentId:
          type: string
        title:
          type: string
        description:
          type: string
        specificDateEvent:
          type: array
          items:
            $ref: '#/components/schemas/SpecificDateEvent'
      required:
        - contentId
        - title
        - description
        - specificDateEvent

    ContentList:
      type: object
      properties:
        anime:
          type: array
          items:
            $ref: '#/components/schemas/AnimeContent'
        radio:
          type: array
          items:
            $ref: '#/components/schemas/RadioContent'
        live:
          type: array
          items:
            $ref: '#/components/schemas/LiveContent'
      required:
        - anime
        - radio
        - live

    ActorsResponse:
      type: object
      properties:
        actors:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
      required:
          - actors

    ActorContentsResponse:
      type: object
      properties:
        Actor:
          $ref: '#/components/schemas/Actor'
        contents:
          $ref: '#/components/schemas/ContentList'
      required:
        - Actor
        - contents

paths:
  /healthcheck:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: 情報の取得成功
      summary: ヘルスチェック用エンドポイント

  /v1/actors:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorsResponse'
          description: 演者一覧の取得成功

  /v1/actors/{actorId}/contents:
    get:
      parameters:
        - name: actorId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorContentsResponse'
          description: 演者のコンテンツ一覧の取得成功
      summary: 演者のコンテンツ一覧を取得するエンドポイント
