openapi: 3.0.0
info:
  title: Go API
  description: local go api
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /healthcheck:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: 情報の取得成功
      summary: ヘルスチェック用エンドポイント
components:
  schemas:
    HealthCheckResponse:
      type: object
      properties:
        status:
          type: string
      required:
        - status
